### ISSUE TITLE
Versioning is unclear

### ISSUE THREAD

**Issue by thirtytwobits** [UAVCAN/pyuavcan#108]
People are doing pip install and expecting a version compatible with what they've been using (v0) but are instead getting the v1 versions. We need to fix this in one of two ways:

1. delete the v1 versions released as >= 0.2 and start releasing these as >= 1.x
2. Create a new pypi project that is pyuavcan1 (or something similar).

**Comment by pavel-kirienko** [comment]
v0 is `uavcan` on PyPI
v1 is `pyuavcan` on PyPI

**Comment by thirtytwobits** [comment]
so v0 versions are 1.x and v1 versions are 0.x? This is really confusing.

**Comment by pavel-kirienko** [comment]
Yes, unfortunately https://github.com/UAVCAN/pyuavcan/issues/97. We could any of the following, as I see it:

- Unrelease all v1.x.x, and re-release the latest v1.0.0.dev32 as v0.0.1.
- Keep things as-is.
- Release PyUAVCAN v1.0 but with a note that API stability is not yet guaranteed until v1.1.

**Comment by thirtytwobits** [comment]
what about changing pyuavcan to use v1.1.x.unstable?
