### ISSUE TITLE
UDP localhost transport is not working on macOS

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/pyuavcan#113]
@thirtytwobits and @arrowcircle say that the UDP transport is not working on localhost on macOS in https://github.com/UAVCAN/Yukon/pull/46#issuecomment-628644462.

I am unable to reproduce because I don't have any macOS computers within reach. Maybe it's worth looking into veth tunnels or similar alternatives if there are any on macOS, like https://stackoverflow.com/questions/58080648/broadcast-packets-do-not-propagate-through-a-linux-veth-tunnel/58118503.

If a solution is found, it should be described in the docs. If not, it should also be stated there as a known issue.

**Comment by arrowcircle** [comment]
Do we have any test suite or example, that fails? Or should we extract it from Yukon?

**Comment by pavel-kirienko** [comment]
Maybe you could try the demo https://pyuavcan.readthedocs.io/en/latest/pages/usage.html
