### ISSUE TITLE
[UAVCAN v0] Release the legacy library as `pyuavcan_v0` to avoid compatibility issues

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/pyuavcan#166]
See "Legacy considerations" at https://pyuavcan.readthedocs.io/en/stable/pages/installation.html#legacy-considerations

Context at https://forum.uavcan.org/t/problems-with-ds-015/1219/41?u=pavel.kirienko

FYI @tridge

**Comment by PrincePepper** [comment]
Tell me, is there a big difference between `uavcan` and `pyuavcan_v0` now, or has only the name changed?

**Comment by pavel-kirienko** [comment]
Only the name has changed.

**Comment by PrincePepper** [comment]
Thanks for the answer! In the meantime, I'm too lazy to change in the project 😂

**Comment by pavel-kirienko** [comment]
Unless you require compatibility with ArduPilot, you should really switch to UAVCAN v1, which is fully supported by [PyUAVCAN v1.2](https://pyuavcan.readthedocs.io).
