### ISSUE TITLE
It is so difficult for newer to use pyuavcan!

### ISSUE THREAD

**Issue by zhangshengping** [UAVCAN/pyuavcan#169]
It is so difficult for newer to use pyuavcan!
If I just want to use custom define data struct such as {int32 x, int32 y}, and sub/pub data, 
**it is so difficult to get it works on socket can!**

**Comment by pavel-kirienko** [comment]
The demo should get you started: https://pyuavcan.readthedocs.io/en/stable/pages/demo.html

Is there any actionable question or proposal you would like to introduce?
