### ISSUE TITLE
Switch to Github Actions

### ISSUE THREAD

**Issue by coderkalyan** [UAVCAN/pyuavcan#172]
@pavel-kirienko Anything against switching to github actions for pyuavcan (and possibly other projects as well)? It would simplify the workflow to be able to use a single CI framework instead of a different one per repository :smile: There is an official action for PyPI releases as well so that shouldn't be an issue.

**Comment by pavel-kirienko** [comment]
The last time I checked it didn't support Windows hosts. Does it now? If not then it is probably a no-go.

**Comment by pavel-kirienko** [comment]
Closing as low-priority -- the AppVeyor's CI is not broken so let us not fix it at least for now. Moving it to a different provider is not expected to be easy.
