### ISSUE TITLE
This repo has incorrect info about the status of 'v0' .

### ISSUE THREAD

**Issue by davidbuzz** [UAVCAN/pyuavcan#206]
The 'legacy-v0' branch, for example, is poorly named, and the README makes no mention of where to find the code formerly known as 'v0'. It would be more accurate to say that many in the community have decided to fork it elsewhere and move forward with 'v0' under a new name, as it's well-proven and widely deployed.  
New url: https://github.com/dronecan/pydronecan
New name: DroneCan

**Comment by pavel-kirienko** [comment]
Addressed in #207, #208. Thanks!
