### ISSUE TITLE
Implement caching for dsdl signatures

### ISSUE THREAD

**Issue by NerdyProjects** [UAVCAN/pyuavcan#49]
Running pyuavcan on a raspberry pi to log stuff into influx db, I encounter high CPU load on ~20 packets/s so I get packet loss. Profiling revealed a lot of time (>75%) spent in the dsdl signature calculation.
 
In `parser.py`, there is a cache that is local to each instance of a type (`_data_type_signature`), but that seems to not be in effect here (I did not dig deep to understand the lifecycle of the type objects).
Adding a simple cache to `compute_signature` (`signature.py`) helped solving my CPU load problem. From 100% with packet loss to ~50 % without packet loss. Profiling shows still some time calculating signatures, but magnitudes less impact than before.

See https://github.com/NerdyProjects/pyuavcan/commit/e358444649a58772eedbfefa0978e2b2796528a0 for a simple solution. As that is only python3, I did not create a pull request but leave this issue to further discussion.

In my opinion, the parser should get a type-global cache that would be even more effective, but my solution works easily, reliable and good enough.

**Comment by pavel-kirienko** [comment]
> Adding a simple cache to compute_signature (signature.py) helped solving my CPU load problem. 

Like `functools.lru_cache`? That would make sense, I think. Could you send a PR?

**Comment by pavel-kirienko** [comment]
@NerdyProjects do we still care or should I close this? This issue does not affect the new version (which is rewritten from scratch, this time with architecture and tests).

**Comment by NerdyProjects** [comment]
Oh, sorry, I don't spend much time in this project anymore in the last months :-( Please close, I have too many things on my mind to care about it in the next weeks, especially if you have a new approach :-)
Thanks a lot for your work and effort!
