### ISSUE TITLE
TAO removal

### ISSUE THREAD

**Issue by windelbouwman** [UAVCAN/pyuavcan#54]
I understood that the TAO (tail array optimization) will be removed from the protocol. Is this already the case for pyuavcan? If I check the sourcecode, I think TAO is still in use.

**Comment by pavel-kirienko** [comment]
> I understood that the TAO (tail array optimization) will be removed from the protocol.

It will no longer be used in UAVCAN v1.0, the first stable release of the protocol. PyUAVCAN does not yet support UAVCAN v1.0, there is a rewrite in progress.

**Comment by windelbouwman** [comment]
Okay, I submitted a pull request repairing the TAO in libcanard: https://github.com/UAVCAN/libcanard/pull/116
