### ISSUE TITLE
Python-CAN media driver

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/pyuavcan#63]
Basically, we need this reimplemented for PyUAVCAN v1.0: https://github.com/UAVCAN/pyuavcan/pull/53

@windelbouwman @adolfogc could use your help here!

**Comment by adolfogc** [comment]
Hi @pavel-kirienko, I'm in the process of studying the UAVCAN v1.0 specification and getting familiar with PyUAVCAN's v1.0 branch. After this, I would like to start working on adding support for SocketCAN using Python-CAN.

**Comment by pavel-kirienko** [comment]
@adolfogc this is cool. Please observe that there is a SocketCAN media implementation in the upstream already; it makes sense to focus on other devices supported by Python-CAN.

**Comment by pavel-kirienko** [comment]
Hey @adolfogc is there still interest?

**Comment by jxltom** [comment]
Since python-can supports socketcan natively, it might make sense that the current socketcan media driver can be removed.

**Comment by pavel-kirienko** [comment]
Implemented in #123
