### ISSUE TITLE
the defer function can't pass parameters as input to the callback function

### ISSUE THREAD

**Issue by yudinghong** [UAVCAN/pyuavcan#67]
the defer function can't pass parameters as input to the callback function, can you do some change on this function?

**Comment by pavel-kirienko** [comment]
Use closures instead https://en.wikipedia.org/wiki/Closure_(computer_programming)

**Comment by yudinghong** [comment]
Thanks for your reply, I will read this page and try

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
