### ISSUE TITLE
tox?

### ISSUE THREAD

**Issue by pavel-kirienko** [UAVCAN/pyuavcan#87]
The test suite consists mostly of complex functional tests that require a particular configuration of the environment. The configuration is enforced by the test script `test.sh`, and also its much-simplified counterpart with reduced functionality for Windows `test.ps1`.

Do we want to convert it into Tox?

**Comment by thirtytwobits** [comment]
Yes

**Comment by pavel-kirienko** [comment]
why

**Comment by thirtytwobits** [comment]
It coordinates testing across multiple python versions. tox.ini is also a defacto standard for configuring your test environment.

**Comment by pavel-kirienko** [comment]
Closing as low priority.
